version: '3.7'
volumes:
  postgres-data:
  bundle:
services:
  postgres:
    image: postgres:11.7
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: redis
    ports:
      - '6379:6379'
  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - postgres
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - '.env'
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - /app/tmp
  tailwind:
    build: .
    command: bundle exec rails tailwindcss:watch
    depends_on:
      - postgres
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - '.env'
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - /app/tmp
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - /app/tmp
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - '.env'
